services:
  - type: web
    name: halalergy-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: APT_PACKAGES
        value: tesseract-ocr tesseract-ocr-ind tesseract-ocr-eng libgl1-mesa-glx
      - key: PYTHON_VERSION
        value: 3.10.10